# Generated by Django 4.0.5 on 2022-06-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
